version: "3.9"
    
services:
  postgresql:
    container_name: piscineds
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    expose:
      - 5432